### ISSUE TITLE
React group project: set up your Kanban board

### ISSUE THREAD

**Issue by Yilikal250** [Yilikal250/Space-Travelers-Hub22#25]
- [x] On the Project that we are doing this week our group members are 3 and this is the link to our [project](https://github.com/Yilikal250/Space-Travelers-Hub22/projects/1).

**Comment by codepantha** [comment]
Hi team, 

Your kanban setup is complete!  There is nothing else to say other than... it's time to start your project :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
